version: '3.7'
services:

    db:
        image: aprismatic/mssql-server-windows-developer-fulltext:latest
        container_name: prismadb_mssql_db
        networks:
            - prismadb
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "Qwer!234"
            ACCEPT_EULA: "Y"

    proxy:
        image: aprismatic/prismadb-proxy-mssql-trial:win-1809
        container_name: prismadb_mssql_proxy
        networks:
            - prismadb
        ports:
            - 4000:4000
        depends_on:
            - db
        environment:
            ListenPort: "4000"
            DataSource: "db"
            InitialCatalog: "testdb"

networks:
    prismadb: